name: Release Theater Actor

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v0.1.0, v1.2.3, etc.

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build and prepare release
        uses: ./.github/actions/release-actor
        
      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          
          # Extract major and minor versions for moving tags
          if [[ $VERSION =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
            MAJOR="${BASH_REMATCH[1]}"
            MINOR="${BASH_REMATCH[2]}"
            PATCH="${BASH_REMATCH[3]}"
            echo "MAJOR=v${MAJOR}" >> $GITHUB_OUTPUT
            echo "MINOR=v${MAJOR}.${MINOR}" >> $GITHUB_OUTPUT
          fi
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            component.wasm
            manifest.toml
            init.json
          body: |
            ## 🎭 ${{ github.event.repository.name }} ${{ steps.version.outputs.VERSION }}
            
            This release contains the WebAssembly component and configuration files for the **${{ github.event.repository.name }}** actor.
            
            ### 📦 What's Included
            - `component.wasm` - The compiled WebAssembly actor component
            - `manifest.toml` - Actor manifest with GitHub release URLs
            - `init.json` - Initial state configuration (if applicable)
            
            ### 🚀 Quick Start
            
            **Prerequisites:**
            - Install and configure the `theater` CLI tool
            - Ensure `theater-server-cli` is running
            
            **Run the actor:**
            ```bash
            theater start https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.VERSION }}/manifest.toml
            ```
            
            ### 🔗 Manifest URLs
            
            **Specific version:**
            ```
            https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.VERSION }}/manifest.toml
            ```
            
            **Latest in minor series (recommended for dependencies):**
            ```
            https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.MINOR }}/manifest.toml
            ```
            
            **Latest in major series:**
            ```
            https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.MAJOR }}/manifest.toml
            ```
            
            ### 📖 About
            This is a theater actor built with Rust and compiled to WebAssembly. It can be deployed and managed within the theater actor system for distributed computing tasks.
            
            For more details about this actor's capabilities, check the repository documentation.
            
            ---
            
            **Repository:** [${{ github.repository }}](https://github.com/${{ github.repository }})  
            **Release:** ${{ steps.version.outputs.VERSION }}  
            **Build:** [${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update moving tags
        if: steps.version.outputs.MAJOR != '' && steps.version.outputs.MINOR != ''
        run: |
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Create/update major version tag (e.g., v0 points to latest v0.x.x)
          git tag -f ${{ steps.version.outputs.MAJOR }} ${{ steps.version.outputs.VERSION }}
          git push origin ${{ steps.version.outputs.MAJOR }} --force
          
          # Create/update minor version tag (e.g., v0.1 points to latest v0.1.x)
          git tag -f ${{ steps.version.outputs.MINOR }} ${{ steps.version.outputs.VERSION }}
          git push origin ${{ steps.version.outputs.MINOR }} --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
